import React, { useState } from 'react'
import { useRouter } from 'next/router'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Button from './_button'
import Urbanfit_logo from '../public/U-logo1 1 1.png'

// configuring inter font
const inter = Inter({ subsets: ['latin'] })


export default function Signing(props) {
    const { page } = props
    console.log(page)

    // configuring router
    const router = useRouter()

    //handling user input details with state hook and onchange event
    const initialFormObj = {
        username: '',
        email: '',
        phone: '',
        password: '',
    }
    const [credentials, setCredentials] = useState(initialFormObj)
    const onchange = (e) => {
        setCredentials({ ...credentials, [e.target.name]: e.target.value })
        console.log(credentials)
    }

    //handling onsubmit event and applying frontend validation
    const onsubmit = (e) => {
        e.preventDefault()
        if (credentials) {
            // yet to do according to the backend API
        }
    }

    //button value renderer
    const btnvalue = () => {
        if (props.type === 'forgotpass') return 'Verify'
        if (page === 'login' || props.type === 'resetpass') return 'Login';
        if (page === 'signup') return 'Sign Up';
    }
    return (
        <>
            <Head>
                <title>Urban Fits - {page === 'login' ? 'Login' : 'Sign Up'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className={`bg-white lg:overflow-x-hidden`}>
                <section className='lg:flex lg:items-center lg:justify-center lg:w-screen lg:h-screen' >
                    <div className=" w-[95%] md:w-[407px] mt-16 lg:mt-0 mx-auto ">
                        <Image src={Urbanfit_logo} alt="Urbanfits Logo" className={`${page === 'login' ? 'hidden' : ''} mx-auto mb-3`} />
                        <div className='w-full mx-auto mb-7' >
                            <h2 className="font_futuraLT font-medium text-4xl leading-[47px] text-center">Join Our Urban Program <br /> and get free Shipping <br /> & free returns on <br /> every order</h2>
                        </div>
                        <div className='w-[304px] mx-auto leading-8' >
                            <h3 className=" font-light text-2xl text-center">Urban Members get Exclusive <br /> access to products, events, <br /> and offers. Just provide a <br /> few details. It’s free to join and <br /> open to all.</h3>
                        </div>
                    </div>

                    <div className=" w-[95%] md:w-[400px] mx-auto py-7 bg-white">
                        <Image src={Urbanfit_logo} alt="Urbanfits Logo" className={`${page === 'login' ? '' : 'hidden'} mx-auto mb-8`} />
                        <div className={`${router.pathname==='/login' ? '' : 'hidden'} w-full mt-3 mb-5 flex justify-center space-x-6`}>
                            <button className="w-1/2 py-2 px-9 bg-gray-100 border border-gray-400 rounded-full hover:shadow-xl transition"><a href="#" title="Continue with Google" className='text-lg font-semibold flex items-center space-x-3'><img src="https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png" className='inline' width="28" alt="google" /><p>Google</p></a></button>
                            <button className="w-1/2 py-2 px-9 border border-black bg-black text-white rounded-full hover:shadow-xl transition"><a href="#" title="Continue with Google" className='text-lg font-semibold flex items-center space-x-3'><img src="https://www.freepnglogos.com/uploads/mac-cosmetic-png-logo/apple-mac-cosmetic-png-logo-8.png" className='inline translate-y-[-1px]' width="33" alt="google" /><p>Apple</p></a></button>
                        </div>
                        <form className="bg-white p-2 font_futuraLT" onSubmit={onsubmit} >
                            <div className={`data_field ${page === 'login' ? 'hidden' : ''} flex items-center border-b  focus:border-yellow-700 hover:border-yellow-600 transition py-2 px-3 mb-4`}>
                                <input className="pl-2 outline-none border-none" type="text" name="username" id="username" onChange={onchange} placeholder="Username" />
                            </div>
                            <div className="data_field lex items-center border-b  focus:border-yellow-700 hover:border-yellow-600 transition py-2 px-3 mb-4">
                                <input className="pl-2 outline-none border-none" type="email" name="email" id="email" onChange={onchange} placeholder="Email" />
                            </div>
                            <div className={`data_field ${page === 'login' ? 'hidden' : ''} flex items-center border-b  focus:border-yellow-700 hover:border-yellow-600 transition py-2 px-3 mb-4`}>
                                <input className="pl-2 outline-none border-none" type='number' name="phone" id="phone" onChange={onchange} placeholder="Phone No." />
                            </div>
                            <div className={` ${props.type === 'forgotpass' ? 'hidden' : ''} data_field lex items-center border-b  focus:border-yellow-700 hover:border-yellow-600 transition py-2 px-3 mb-4`}>
                                <input className="pl-2 outline-none border-none" type='password' name="password" id="password" onChange={onchange} placeholder="Password" />
                            </div>
                            <div className={` ${props.type === 'resetpass' ? '' : 'hidden'} data_field lex items-center border-b  focus:border-yellow-700 hover:border-yellow-600 transition py-2 px-3`}>
                                <input className="pl-2 outline-none border-none" type='password' name="reppassword" id="reppassword" onChange={onchange} placeholder="Repeat Password" />
                            </div>
                            <div className="my-3">
                                <small className='text-gray-400 text-xs '>{props.type === 'forgotpass' ? 'Please enter your username or email address. You will receive an email message with instructions on how to reset your password.' : 'Password must be at least 8 characters and can’t be easy to guess - commonly used or risky passwords are not premitted.'}</small>
                            </div>
                            <div className={`${props.type === 'forgotpass' ? 'hidden' : ''} w-full h-14 mb-3 flex items-center border-b`}>
                                <div className='mx-2' >
                                    <input className='' type="checkbox" id="todo" name="todo" value="todo" />
                                </div>
                                <div className=' text-left h-full flex items-center' >
                                    <label htmlFor="todo"><small className="ml-1 text-xs text-gray-400">{page === 'login' ? 'Rmember me' : 'Buy creating an account, I agree to the Terms & Conditions.I have read the Legal Notice and Privacy Policy'}</small></label>
                                </div>
                            </div>
                            <Button value={btnvalue()} classes='w-full' />
                            <Link href={page === 'login' ? '/signup' : '/login'} className='underline underline-offset-1'><h1 className='w-full text-center' >{page === 'login' ? 'Create a New Account' : 'Log in with an Existing Account'}</h1></Link>
                            <div className={`${page === 'login' ? 'hidden' : ''} ${inter.className} w-full mt-5 flex justify-center space-x-6`}>
                                <button className="w-1/2 py-2 px-9 bg-gray-100 border border-gray-400 rounded-full hover:shadow-xl transition"><a href="#" title="Continue with Google" className='text-lg flex items-center space-x-3'><img src="https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png" className='inline' width="28" alt="google" /><p>Google</p></a></button>
                                <button className="w-1/2 py-2 px-9 border border-black bg-black text-white rounded-full hover:shadow-xl transition"><a href="#" title="Continue with Google" className='text-lg flex items-center space-x-3'><img src="https://www.freepnglogos.com/uploads/mac-cosmetic-png-logo/apple-mac-cosmetic-png-logo-8.png" className='inline translate-y-[-1px]' width="33" alt="google" /><p>Apple</p></a></button>
                            </div>
                        </form>
                    </div>
                </section>

                <div className="w-full my-5 px-10 font_futuraLT flex flex-col lg:flex-row justify-between lg:space-x-3">
                    <Button value="Home" classes='w-full' />
                    <Button value="Catelog" classes='w-full' />
                    <Button value="Contact Us" classes='w-full' />
                    <Button value="Privacy Policy" classes='w-full' />
                    <Button value="Legal Notice" classes='w-full' />
                    <Button value="Terms & Condition" classes='w-full' />
                </div>
            </main>
        </>
    )
}
