import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "@/components/footer";
import Carousel from "@/components/carousels/carousel";
import CardCarousel from "@/components/carousels/cardCarousel";
import Card from "@/components/cards/card";
import PicCard from "@/components/cards/picCard";
// Modal imports
import LoadingModal from "../components/modals/loadingmodal";
import LanguageModal from "../components/modals/languagemodal";
// imports for images
import Image from "next/image";
import Logo from "../public/logos/logo_black.svg";
import image1 from "../public/card imgs/card img5.jpg";
import image2 from "../public/card imgs/card img6.jpg";
import image3 from "../public/card imgs/card img1.jpg";
import image4 from "../public/card imgs/card img8.jpg";

export default function Home() {
    // state for navbar expansion
    const [expand, setExpand] = useState(false);
    // states and function for modals
    const [modal1, setModal1] = useState(false);
    const [modal3, setModal3] = useState(false);

    useEffect(() => {
        let item = localStorage.getItem("loadingModal");
        if (item) return;
        setModal1(true);
        localStorage.setItem("loadingModal", true);
    }, []);

    useEffect(() => {
        let carousel = document.querySelector("#carousel");
        let wrapper = document.querySelector("#content_wrapper");
        let navbar = document.querySelector("#navbar");
        navbar.classList.add("opacity-0", "pointer-events-none");
        const setSizefunc=()=>{
            let position = window.pageYOffset;
            if (position >> 0) {
                carousel.classList.add(
                    'lg:w-4/5',
                    'w-11/12',
                    'h-80vh',
                    'rounded-2rem',
                    'mt-7',
                    'mx-auto',
                    'lg:m-10');
                wrapper.classList.add('lg:w-[94.6%]');
                navbar.classList.remove('opacity-0', 'pointer-events-none')
                window.removeEventListener('scroll', setSizefunc);
            }
        }
        window.addEventListener('scroll', setSizefunc);
    }, []);

    const toggleModal = (e) => {
        if (e.target.name === "modal1") {
            if (modal1 === false) return setModal1(true);
            if (modal1 === true) return setModal1(false);
        } else if (e.target.name === "modal3") {
            if (modal3 === false) return setModal3(true);
            if (modal3 === true) return setModal3(false);
        }
    };

    return (
        <>
            <Head>
                <title>Urban Fits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className="w-full h-full section_container">
                <Navbar logoNull transition="duration-700 ease-linear" setExpand={setExpand} />
                <LoadingModal show={modal1} toggleModal={toggleModal} />
                <LanguageModal show={modal3} toggleModal={toggleModal} />
                <section className={`${expand === true ? "w-full lg:w-4/5" : "w-full"} bg-gray-100 float-right flex justify-center lg:justify-end transition-all ease-linear duration-700`} >
                    <Image alt="Urban images" src={Logo} className="fixed top-6 right-6 md:top-10 md:right-10 z-10 w-14 md:w-20" />
                    <div id="content_wrapper" className="w-full flex flex-col justify-center items-center space-y-5 transition-all ease-linear duration-700" >
                        <div id="carousel" className="w-full h-screen font_futuraLT transition-all duration-1000 ease-linear overflow-hidden" >
                            <Carousel />
                        </div>
                        {/* Auto scroll Carousel  */}
                        <section className="relative w-full h-80vh lg:h-screen p-3 md:p-5 md:pr-0 flex flex-col md:flex-row items-center justify-center font_futuraLT">
                            <div className="w-full md:w-35pr md:h-full p-5 flex flex-col justify-center items-start">
                                <h2 className="text-2xl md:text-4xl lg:text-5xl word-wrap leading-tight">
                                    Newest Gear to Work
                                </h2>
                                <h4 className="font_futuraLTlite text-lg">
                                    Innovation and Comfort for Women
                                </h4>
                            </div>
                            <div className="w-full md:w-70pr h-full flex items-center">
                                <CardCarousel />
                            </div>
                            <div className="absolute w-1/5 h-full top-0 right-0 bg-gradient-to-l from-white to-transparent pointer-events-none"></div>
                        </section>
                        {/* Shopping Card Section */}
                        <section className="w-full h-screen p-3 md:p-10 flex flex-col lg:flex-row justify-between font_futuraLT space-y-7 lg:space-y-0 snap-center">
                            <PicCard img={image1} />
                            <PicCard img={image2} />
                        </section>
                        {/* Shopping Card Section */}
                        <section className="w-full font_futuraLT snap-center">
                            <h3 className="text-4xl mx-3 md:ml-10">Urban Unicorn Sneakers</h3>
                            <div className="w-full h-screen p-3 md:p-10 flex flex-col lg:flex-row justify-between space-y-7 lg:space-y-0">
                                <PicCard img={image4} />
                                <PicCard img={image3} />
                            </div>
                        </section>
                        {/* Auto scroll Carousel  */}
                        <section className="relative w-full h-80vh lg:h-screen p-3 md:p-5 md:pr-0 flex flex-col md:flex-row font_futuraLT snap-center">
                            <div className="w-full md:w-35pr md:h-full p-5 flex flex-col justify-center items-start">
                                <h2 className="text-2xl md:text-4xl lg:text-5xl word-wrap leading-tight self-start">
                                    Newest Gear to Work
                                </h2>
                                <h4 className="font_futuraLTlite text-lg">
                                    Innovation and Comfort for Men
                                </h4>
                            </div>
                            <div className="w-full md:w-70pr h-full flex items-center">
                                <CardCarousel />
                            </div>
                            <div className="absolute w-1/5 h-full top-0 right-0 bg-gradient-to-l from-white to-transparent pointer-events-none"></div>
                        </section>
                        {/* Ending Link Cards section */}
                        <section className="w-full h-auto lg:h-80vh p-5 flex flex-col lg:flex-row justify-around items-center space-y-6 lg:space-y-0">
                            <Card href="/contact" title="Contact Us" value="If you have any query then please contact us." valueCenter btnValue="Contact Us" classes="w-full md:w-60vw py-20 justify-center items-center h-full lg:w-30pr md:h-3/4" />
                            <Card href="/customercare" title="Customer Care" value="Do you have any questions? We are here to help you. You can contact our customer care team by email or over the phone." valueCenter btnValue="Get In Touch" classes="lg:scale-110 w-full md:w-60vw py-20 justify-center items-center h-full lg:w-30pr md:h-3/4" />
                            <Card href="/faq" title="FAQ" value="Find all the answers to the frequently asked questions below." valueCenter btnValue="See Our FAQs" classes="w-full md:w-60vw py-20 justify-center items-center h-full lg:w-30pr md:h-3/4" />
                        </section>
                        <Footer />
                    </div>
                </section>
            </main>
        </>
    );
}
