import Head from 'next/head'
import React, { useState } from 'react'
import { Inter } from '@next/font/google'
import Button from '../components/link_btn';
import Navbar from '../components/navbar';
import styles from '@/styles/Home.module.css'
import Newsletter from '../components/newsletter';
import LoadingModal from '../components/loadingmodal';
import LanguageModal from '../components/languagemodal';
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [expand, setExpand] = useState(false)

  // states and function for modals
  const [modal1, setModal1] = useState(false)
  const [modal2, setModal2] = useState(false)
  const [modal3, setModal3] = useState(false)
  const toggleModal = (e) => {
    if (e.target.name === "modal1") {
      if (modal1 === false) return setModal1(true)
      if (modal1 === true) return setModal1(false)
    }
    else if (e.target.name === "modal2") {
      if (modal2 === false) return setModal2(true)
      if (modal2 === true) return setModal2(false)
    }
    else if (e.target.name === "modal3") {
      if (modal3 === false) return setModal3(true)
      if (modal3 === true) return setModal3(false)
    }
  }

  return (
    <>
      <Head>
        <title>Urban Fits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar setExpand={setExpand} />
      <LoadingModal show={modal1} toggleModal={toggleModal} />
      <Newsletter show={modal2} toggleModal={toggleModal} />
      <LanguageModal show={modal3} toggleModal={toggleModal} />

      <main className={` ${expand === true ? 'w-3/4' : 'w-full lg:w-[95%]'} w-screen h-screen text-white bg-slate-700 overflow-x-hidden transition-all duration-700 absolute top-0 right-0`}>
        <section className="p-10">

          <h1 className="text-white text-xl md:text-3xl text-center font_futuraLT">Welcome to the Urban Fits</h1>
          <h1 className="text-gray-300 text-lg md:text-2xl text-center">Home Page is not ready yet</h1>

          <Button href="/home" bg="bg-gradient-to-r from-cyan-500 to-blue-500" classes="w-full" >Home Page</Button>
          <Button onclick={toggleModal} name="modal3" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full">Activate Change Language Modal</Button>
          <Button href="/trackorder" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" >Track Your Order Page</Button>
          <Button href="/home" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" >Home page</Button>

          <Button href="/giftcard"  classes="w-full" >Giftcard page</Button>
          <Button onclick={toggleModal} name="modal1" classes="w-full">Activate Change Country Modal</Button>
          <Button onclick={toggleModal} name="modal2" classes="w-full">Activate Newsletter Modal</Button>
          <Button href="/contact" classes="w-full" >Contact Us page</Button>
          <Button href="/forgotpassword" classes="w-full" >Forgot password page</Button>
          <Button href="/resetpassword" classes="w-full" >Reset password page</Button>
        </section>
        <Footer />
      </main>
    </>
  )
}
