import Head from 'next/head'
import React, { useState } from 'react'
import { Inter } from '@next/font/google'
import Button from '../subcomponents/_link_btn';
import Navbar from '../subcomponents/_navbar';
import styles from '@/styles/Home.module.css'
import Newsletter from '../subcomponents/_newsletter';
import LoadingModal from '../subcomponents/_loadingmodal';
import LanguageModal from '../subcomponents/_languagemodal';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [expand, setExpand] = useState(false)

  // states and function for modals
  const [modal1, setModal1] = useState(false)
  const [modal2, setModal2] = useState(false)
  const [modal3, setModal3] = useState(false)
  const toggleModal = (e) => {
    if (e.target.name === "modal1") {
      if (modal1 === false) return setModal1(true)
      if (modal1 === true) return setModal1(false)
    }
    else if (e.target.name === "modal2") {
      if (modal2 === false) return setModal2(true)
      if (modal2 === true) return setModal2(false)
    }
    else if (e.target.name === "modal3") {
      if (modal3 === false) return setModal3(true)
      if (modal3 === true) return setModal3(false)
    }
  }

  return (
    <>
      <Head>
        <title>Urban Fits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar setExpand={setExpand} />
      <LoadingModal show={modal1} toggleModal={toggleModal} />
      <Newsletter show={modal2} toggleModal={toggleModal} />
      <LanguageModal show={modal3} toggleModal={toggleModal} />

      <main className={` ${expand === true ? 'w-3/4' : 'w-full lg:w-[95%]'} w-screen p-10 h-screen text-white bg-slate-700 overflow-x-hidden transition-all duration-700 absolute top-0 right-0`}>
        <h1 className="text-white text-xl md:text-3xl text-center font_futuraLT">Welcome to the Urban Fits</h1>
        <h1 className="text-gray-300 text-lg md:text-2xl text-center">Home Page is not ready yet</h1>

        {/* <Button onclick={toggleModal} name="modal3" value="Activate Language & Country Modal" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" /> */}
        <Button onclick={toggleModal} name="modal1" value="Activate Change Country Modal" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" />
        <Button onclick={toggleModal} name="modal2" value="Activate Newsletter Modal" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" />
        <Button href="/login" value="Log in page" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" ></Button>
        <Button href="/signup" value="Sign up page" bg="bg-gradient-to-r from-purple-500 to-pink-500" classes="w-full" ></Button>

        <Button href="/contact" value="Contact Us page" classes="w-full" ></Button>
        <Button href="/giftcard" value="Giftcard page" classes="w-full" ></Button>
        <Button href="/user/personalinfo" value="My Account page" classes="w-full" ></Button>
        <Button href="/forgotpassword" value="Forgot password page" classes="w-full" ></Button>
        <Button href="/resetpassword" value="Reset password page" classes="w-full" ></Button>
      </main>
    </>
  )
}
