import React, { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Footer from "@/components/footer";
import Link from "next/link";
import Aos from "aos";
import 'aos/dist/aos.css';
import Image from "next/image";
import hero_bg from '@/public/cart/cartbg.jpg'
import img1 from '@/public/stories/img1.jpg'
import img2 from '@/public/stories/img2.jpg'
import img3 from '@/public/stories/img3.jpg'
import img4 from '@/public/stories/img4.jpg'
import img5 from '@/public/stories/img5.jpg'
import img6 from '@/public/stories/img6.jpg'
import img7 from '@/public/stories/img7.jpg'
import img8 from '@/public/stories/img8.jpg'

export default function Storeis() {
    const router = useRouter()
    const {story} = router.query

    useEffect(() => {
        Aos.init()
    }, [])

    return (
        <>
            <Head>
                <title>Storeis - Urban Fits</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar />
            <main className='w-full bg-white transition-all ease-linear duration-500 overflow-hidden' >
                <section className="relative w-full layout_height flex flex-col justify-center items-center gap-y-5 transition-all ease-linear duration-500 overflow-hidden" >
                    <Image width={1400} height={512} src={hero_bg} alt='Storeis background' className="h-full md:w-full absolute top-0 left-0 object-cover object-top" />
                    <div className="z-10 flex flex-col justify-center items-center gap-5">
                        <span className="font_gotham text-white text-sm"><Link className="underline underline-offset-8" href='/' >Main Page</Link> / <Link className="underline underline-offset-8 capitalize" href='/stories' >{story}</Link></span>
                        <h1 className="font_gotham_bold text-2xl md:text-[32px] text-white tracking-[0.15em]">{story.toUpperCase()}</h1>
                    </div>
                </section>
                <section className="w-full lg:px-12 xl:px-16 2xl:px-20 flex flex-col">
                    <div className="w-full px-7 md:px-0 md:w-4/5 -translate-y-[10%]">
                        <Image width={1400} height={500} data-aos-offset='10px' data-aos-duration='1000' data-aos="fade-up-right" src={img1} className="w-full h-full object-cover" />
                    </div>

                    <div className="relative w-full lg:my-28 2xl:my-36 flex flex-col-reverse md:flex-row justify-between">
                        <div className="w-full md:w-[45%] my-5 flex justify-between">
                            <div className="w-48pr h-full">
                                <Image width={1400} height={500} data-aos-duration='1000' data-aos="fade-right" src={img3} className="w-full h-full object-cover" />
                            </div>
                            <div className="w-48pr h-full">
                                <Image width={1400} height={500} data-aos-duration='1000' data-aos-delay='500' data-aos="fade-right" src={img4} className="w-full h-full object-cover" />
                            </div>
                        </div>
                        <div className="w-full px-7 md:px-7 md:w-[35%] md:absolute md:-translate-y-[60%] right-0 ">
                            <Image width={1400} height={500} data-aos-duration='1000' data-aos="fade-up-left" src={img2} className="w-full h-full object-cover" />
                        </div>
                    </div>

                    <div className="relative w-full md:h-[150vh] px-7 md:px-0 gap-y-5 md:gap-y-0 flex flex-col">
                        <div className="md:absolute top-0 right-0 w-full md:w-70pr">
                            <Image width={1400} height={500} data-aos-duration='1000' data-aos="fade-up-right" src={img5} className="w-full h-full object-cover" />
                        </div>
                        <div className="md:absolute bottom-0 left-0 w-full md:w-70pr">
                            <Image width={1400} height={500} data-aos-duration='1000' data-aos="fade-up-left" src={img6} className="w-full h-full object-cover" />
                        </div>
                    </div>

                    <div className="w-full flex justify-end">
                        <div className="w-full md:w-48pr my-5 flex justify-between md:-translate-y-[15%]">
                            <div className="w-48pr h-full">
                                <Image width={1400} height={500} data-aos-duration='1000' data-aos-delay='500' data-aos="fade-left" src={img7} className="w-full h-full object-cover" />
                            </div>
                            <div className="w-48pr h-full">
                                <Image width={1400} height={500} data-aos-duration='1000' data-aos="fade-left" src={img8} className="w-full h-full object-cover" />
                            </div>
                        </div>
                    </div>
                </section>
            </main>
            <Footer />
        </>
    );
}